# Generated by Django 2.0.7 on 2019-12-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jpeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='JpegToPdf/original/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='JpegToPdf/original/')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='JpegToPdf/converted/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='JpegToPdf/original/')),
            ],
        ),
    ]
