# Generated by Django 2.0.7 on 2019-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpeg',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
