# Generated by Django 2.0.7 on 2019-12-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0002_auto_20191223_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jpeg',
            name='cover',
        ),
    ]
