# Generated by Django 2.0.7 on 2019-12-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0003_remove_jpeg_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jpeg',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='name',
            new_name='file_name',
        ),
    ]
