# Generated by Django 2.0.7 on 2019-12-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0004_auto_20191223_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jpeg',
            old_name='file',
            new_name='image_file',
        ),
    ]
