# Generated by Django 2.0.7 on 2019-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0005_auto_20191223_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpeg',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='JpegToPdf/original/'),
        ),
    ]
