# Generated by Django 2.0.7 on 2019-12-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0008_auto_20191227_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='image_file',
            new_name='pdf_file',
        ),
    ]
