# Generated by Django 2.0.7 on 2019-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0009_auto_20191227_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='JpegToPdf/original/'),
        ),
    ]
