# Generated by Django 2.0.7 on 2019-12-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JpegToPdf', '0011_auto_20191228_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='cover',
        ),
    ]
