# Generated by Django 2.0.7 on 2019-12-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PngToPdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jpeg',
            new_name='Png',
        ),
    ]
